#! /bin/ash

mkdir -p /proc
mount -t proc proc /proc
mkdir -p /sys
mount -t sysfs sysfs /sys
mkdir -p /dev/pts
mount -t devpts devpts /dev/pts
echo /sbin/mdev > /proc/sys/kernel/hotplug
mdev -s
hostname qemu
ifconfig lo 127.0.0.1 up
# This board doesn't have a hardware clock, so system time is way off.
# The bugsybox dhcp client doesn't work when the clock is wrong.
# Oh well.
ifconfig eth0 10.0.2.15 up
rdate 10.0.2.2
ip route add default via 10.0.2.2

echo -ne "\nIf you want to load IT keymap, just issue:\n"
echo "loadkmap < /etc/kdump_it"
echo "Or add the above command to /etc/init.d/rcS file."

# or uncomment this :P
# loadkmap < /etc/kdump_it
